name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Code (Check Formatting)
      run: |
        pip install flake8
        flake8 project --count --select=E9,F63,F7,F82 --show-source --statistics || true

    - name: Test API Startup
      run: |
        uvicorn api.main:app --host 127.0.0.1 --port 8000 &
        API_PID=$!
        sleep 5
        curl -f http://127.0.0.1:8000 || (kill $API_PID && exit 1)
        kill $API_PID

    - name: Test Streamlit App Startup
      run: |
        streamlit run streamlit_app/app.py &
        STREAMLIT_PID=$!
        sleep 10
        curl -f http://localhost:8501 || (kill $STREAMLIT_PID && exit 1)
        kill $STREAMLIT_PID

    - name: Success message
      run: echo "✅ CI/CD pipeline completed successfully."
